"""
Test Healing Module - Auto-healing for AI-generated tests.

This module provides automated healing for failing tests generated by the LLM.
It analyzes test failures, identifies LLM mistakes, and uses the LLM to fix them.

Components:
- test_ast_extractor: Extract test structure from generated tests
- pytest_failure_parser: Parse pytest failures and classify errors
- test_healer: Use LLM to fix failing tests
- auto_healing_loop: Orchestrate the complete healing workflow

Usage:
    from src.test_healing import AutoHealingLoop

    loop = AutoHealingLoop(
        target_root="./target",
        generated_tests_dir="tests/generated",
        max_iterations=3
    )

    session = loop.run_healing_loop()
"""

from .auto_healing_loop import AutoHealingLoop, HealingSession, HealingIteration
from .pytest_failure_parser import PytestFailureParser, TestFailure
from .test_ast_extractor import TestASTExtractor
from .test_healer import TestHealer

__all__ = [
    "AutoHealingLoop",
    "HealingSession",
    "HealingIteration",
    "PytestFailureParser",
    "TestFailure",
    "TestASTExtractor",
    "TestHealer",
]

__version__ = "1.0.0"
