[run]
source = .
omit =
    tests/**
    */tests/**
    */conftest.py
    */__init__.py
    # exclude GUI file if you’re not exercising it headlessly
    ; SimpleCalculatorPyQt1.py

[report]
show_missing = True
skip_covered = True
