[pytest]
addopts = --cov=. --cov-config=coverage.ini \
          --cov-report=term-missing:skip-covered \
          --cov-report=xml:reports/tests/coverage.xml \
          --cov-report=json:reports/tests/coverage.json
