from __future__ import annotations

"""
Generates three types of tests (unit, integration, e2e) using **Azure OpenAI only**.
No local fallbacks. If Azure is not configured, the generator stops with an error.
"""

from pathlib import Path
from typing import Dict, Any, List, Optional
from providers.azure_openai_provider import AzureProvider

HEADER = "# Auto-generated by AI-TestGen (Azure-only). Edit as needed.\n\n"

def _ensure_azure():
    prov = AzureProvider()
    if not prov.available():
        raise RuntimeError("Azure OpenAI is not configured (AZURE_OPENAI_*). This generator is Azure-only.")
    return prov

def _write(path: Path, content: str) -> bool:
    if not content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content if content.startswith("#") else (HEADER + content), encoding="utf-8")
    return True

def _ensure_django_conftest(out_root: Path, settings_module: Optional[str] = None):
    out_root.mkdir(parents=True, exist_ok=True)
    p = out_root / "conftest.py"
    if p.exists():
        return
    p.write_text(
        "# Auto-generated test harness for Django projects (not a test).\n"
        "import os, pytest\n"
        "try:\n"
        "    import collections, collections.abc\n"
        "    for _n in ('Mapping','MutableMapping','Iterable','Iterator'):\n"
        "        if not hasattr(collections, _n):\n"
        "            setattr(collections, _n, getattr(collections.abc, _n))\n"
        "except Exception:\n"
        "    pass\n\n"
        "os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'settings')\n"
        "import django\n"
        "django.setup()\n\n"
        "@pytest.fixture\n"
        "def client():\n"
        "    from django.test import Client\n"
        "    return Client()\n",
        encoding="utf-8",
    )

def generate_pytests(repo_root: Path, analyses: List[Dict[str, Any]], out_dir: Path) -> List[Path]:
    prov = _ensure_azure()

    unit_dir = out_dir / "unit"
    integ_dir = out_dir / "integration"
    e2e_dir  = out_dir / "e2e"
    created: List[Path] = []

    project_ctx = {
        "repo_root": str(repo_root),
        "routes": [],
        "cli": {"has_click": False, "typer_apps": [], "has_argparse": False},
        "modules": [],
    }
    for f in analyses:
        project_ctx["modules"].append({"module": f.get("module"), "path": f.get("path")})
        for r in f.get("routes", []):
            project_ctx["routes"].append({"module": f.get("module"), **r})
        cli = f.get("cli", {})
        if cli.get("click"): project_ctx["cli"]["has_click"] = True
        if cli.get("typer_app"): project_ctx["cli"]["typer_apps"].append({"module": f.get("module"), "app": cli.get("typer_app")})
        if cli.get("argparse"): project_ctx["cli"]["has_argparse"] = True

    _ensure_django_conftest(out_dir, None)

    # Unit tests per file
    for f in analyses:
        module = f.get("module")
        if not module: 
            continue
        pth = f.get("path","")
        if "/tests/" in pth or "\\tests\\" in pth:
            continue
        code = prov.gen_unit(f)
        if code:
            p = unit_dir / f"test_{Path(pth).stem}.py"
            if _write(p, code): created.append(p)

    # Integration tests (project-level)
    in_code = prov.gen_integration(project_ctx)
    if in_code:
        p = integ_dir / "test_integration_auto.py"
        if _write(p, in_code): created.append(p)

    # E2E tests (project-level)
    e_code = prov.gen_e2e(project_ctx)
    if e_code:
        p = e2e_dir / "test_e2e_auto.py"
        if _write(p, e_code): created.append(p)

    return created
