import os
import json
import sys
from typing import List, Dict

def looks_like_ai_generated(path: str, content: str = "") -> bool:
    """Detect AI-generated test indicators in paths or contents."""
    ai_keywords = [
        "ai-generated", "automated test generation", "generated by ai",
        "tests/generated", "universal test suite", "autotestgen"
    ]
    path_lower = path.lower()
    if "generated" in path_lower or "autogen" in path_lower:
        return True
    return any(k in content.lower() for k in ai_keywords)


def find_all_manual_test_dirs(repo_root: str = ".") -> Dict[str, List[str]]:
    """
    Finds all valid manual test directories.
    ✅ Only includes folders that contain .py test files
    🚫 Skips generated/AI test folders
    """
    candidate_dirs = {}

    for root, dirs, files in os.walk(repo_root):
        # Skip AI-generated or irrelevant folders early
        if "generated" in root.lower() or "autogen" in root.lower():
            continue

        dirname = os.path.basename(root).lower()
        if dirname not in ["tests", "test", "testing", "testsuite"]:
            continue

        test_files = []
        for file in files:
            if file.endswith(".py") and (
                file.startswith("test_") or file.endswith("_test.py") or "test" in file.lower()
            ):
                file_path = os.path.join(root, file)
                try:
                    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                        content = f.read()
                    if not looks_like_ai_generated(file_path, content):
                        test_files.append(file_path)
                except Exception:
                    continue

        if test_files:
            candidate_dirs[root] = test_files

    return candidate_dirs


def main():
    """Main entry point for detecting all manual test directories."""
    repo_root = sys.argv[1] if len(sys.argv) > 1 else "."

    print(f"🔍 Scanning repository for manual test directories in: {os.path.abspath(repo_root)}")

    manual_test_dirs = find_all_manual_test_dirs(repo_root)

    if not manual_test_dirs:
        print("⚠️ No manual test directories found.")
        result = {
            "manual_tests_found": False,
            "manual_test_paths": [],
            "test_files_count": 0
        }
    else:
        result = {
            "manual_tests_found": True,
            "manual_test_paths": list(manual_test_dirs.keys()),
            "test_files_count": sum(len(files) for files in manual_test_dirs.values()),
            "test_dirs_detail": manual_test_dirs
        }

    print("\n📊 Detection Result:")
    print(json.dumps(result, indent=2))

    # Write outputs for GitHub Actions
    if "GITHUB_OUTPUT" in os.environ:
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"manual_tests_found={str(result['manual_tests_found']).lower()}\n")
            f.write(f"manual_test_paths={json.dumps(result['manual_test_paths'])}\n")
            f.write(f"test_files_count={result['test_files_count']}\n")

    # Optional: Save detailed result for debugging
    with open("manual_test_result.json", "w") as f:
        json.dump(result, f, indent=2)

    return 0 if result["manual_tests_found"] else 1


if __name__ == "__main__":
    sys.exit(main())
