from __future__ import annotations
"""
Generates developer-style Unit / Integration / E2E tests for *any* Python framework.
- Unit: AI-backed with deterministic fallback (skips migrations & test files)
- Integration/E2E:
    * FastAPI (TestClient), Flask (test_client), Django (pytest-django Client)
    * CLI: Click/Typer (CliRunner), argparse (monkeypatched sys.argv)
    * Generic: conservative smoke tests (optional)
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Any, List, Optional
import re

try:
    from providers.azure_openai_provider import AzureProvider
except Exception:
    AzureProvider = None  # type: ignore

HEADER = "# Auto-generated by AI-TestGen. Edit as needed.\n\n"

# ---- Heuristics for frameworks ----
FASTAPI_APP_RE = re.compile(r"\b([A-Za-z_][\w]*)\s*=\s*FastAPI\s*\(")
FASTAPI_ROUTE_RE = re.compile(r"@\s*([A-Za-z_][\w\.]*)\.(get|post|put|delete|patch)\s*\(\s*(['\"])(.*?)\3")

FLASK_APP_RE = re.compile(r"\b([A-Za-z_][\w]*)\s*=\s*Flask\s*\(")
FLASK_ROUTE_RE = re.compile(r"@\s*([A-Za-z_][\w\.]*)\.route\s*\(\s*(['\"])(.*?)\2")

DJANGO_URLS_PATH_RE = re.compile(r"""path\(\s*['\"]([^'\"]+)['\"]""")
DJANGO_URLS_REPATH_RE = re.compile(r"""re_path\(\s*[r]?['\"]([^'\"]+)['\"]""")

TYPER_APP_RE = re.compile(r"\b([A-Za-z_][\w]*)\s*=\s*typer\.Typer\s*\(")
ARGPARSE_RE = re.compile(r"\bargparse\.ArgumentParser\s*\(")

@dataclass
class Route:
    owner: str
    method: str
    path: str

@dataclass
class FastAPIModule:
    app_name: str
    routes: List[Route]

@dataclass
class FlaskModule:
    app_name: str
    routes: List[Route]

@dataclass
class DjangoProject:
    settings_module: Optional[str]
    urls_files: List[Path]

def _extract_fastapi(source: str) -> Optional[FastAPIModule]:
    m = FASTAPI_APP_RE.search(source)
    app_name = m.group(1) if m else "app"
    routes = [Route(owner=o.split(".")[-1], method=meth.lower(), path=p)
              for o, meth, _, p in FASTAPI_ROUTE_RE.findall(source)]
    return FastAPIModule(app_name, routes) if routes else None

def _extract_flask(source: str) -> Optional[FlaskModule]:
    m = FLASK_APP_RE.search(source)
    app_name = m.group(1) if m else "app"
    routes = [Route(owner=o.split(".")[-1], method="", path=p)
              for o, _, p in FLASK_ROUTE_RE.findall(source)]
    return FlaskModule(app_name, routes) if routes else None

def _detect_django(repo_root: Path) -> Optional[DjangoProject]:
    candidates = []
    for p in repo_root.rglob("settings.py"):
        if "venv" in p.parts or ".venv" in p.parts:
            continue
        if (p.parent / "urls.py").exists():
            candidates.append(p)
    settings_module = None
    if candidates:
        best = min(candidates, key=lambda p: len(p.parts))
        rel = best.relative_to(repo_root).with_suffix("")
        settings_module = ".".join(rel.parts)
    urls_files = [p for p in repo_root.rglob("urls.py") if "venv" not in p.parts and ".venv" not in p.parts]
    if settings_module or urls_files:
        return DjangoProject(settings_module, urls_files)
    return None

def _django_urls_from_file(p: Path) -> List[str]:
    try:
        src = p.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return []
    urls = []
    for m in DJANGO_URLS_PATH_RE.finditer(src):
        u = m.group(1)
        urls.append(u if u.startswith("/") else "/" + u)
    for m in DJANGO_URLS_REPATH_RE.finditer(src):
        urls.append(f"[re_path]{m.group(1)}")
    seen = set(); out = []
    for u in urls:
        if u not in seen:
            seen.add(u); out.append(u)
    return out

def _has_click(source: str) -> bool:
    return "import click" in source or "from click" in source

def _has_typer(source: str) -> Optional[str]:
    m = TYPER_APP_RE.search(source)
    return m.group(1) if m else None

def _has_argparse(source: str) -> bool:
    return bool(ARGPARSE_RE.search(source))

# ---- AI helpers ----
def _ai_unit(module_name: str, analysis: Dict[str, Any]) -> Optional[str]:
    if AzureProvider is None: return None
    try:
        prov = AzureProvider()
        if not prov.available(): return None
        return prov.gen_unit(module_name, analysis.get("path", module_name), analysis.get("source", ""), analysis)
    except Exception:
        return None

def _ai_integ(kind: str, ctx: Dict[str, Any]) -> Optional[str]:
    if AzureProvider is None: return None
    try:
        prov = AzureProvider()
        if not prov.available(): return None
        return prov.gen_integration(kind, ctx)
    except Exception:
        return None

def _ai_e2e(kind: str, ctx: Dict[str, Any]) -> Optional[str]:
    if AzureProvider is None: return None
    try:
        prov = AzureProvider()
        if not prov.available(): return None
        return prov.gen_e2e(kind, ctx)
    except Exception:
        return None

# ---- Deterministic fallbacks ----
def _unit_fallback(module_name: str, analysis: Dict[str, Any]) -> str:
    tests = []
    for fn in analysis.get("functions", []):
        tests.append(f"""
            def test_{fn}_callable():
                assert callable({fn})
        """)
    if not tests:
        tests.append("""
            def test_module_imports():
                assert True
        """)
    code = HEADER + "import pytest\n\n" + "\n".join(t.strip() for t in tests)
    if f"import {module_name}" not in code and f"from {module_name}" not in code:
        code = f"from {module_name} import *\n\n" + code
    return code

def _fastapi_integration(module: str, fapi: FastAPIModule) -> str:
    lines = [HEADER, "import pytest", "from fastapi.testclient import TestClient", f"from {module} import {fapi.app_name} as _app", "", "client = TestClient(_app)", ""]
    for i, r in enumerate(fapi.routes, 1):
        url = re.sub(r"\{[^}]+\}", "1", r.path)
        call = f'client.get("{url}")' if r.method in {"get", ""} else f'client.{r.method}("{url}", json={{}})'
        lines += [f"def test_{r.method or 'get'}_{i}_no_500():", f"    res = {call}", "    assert res.status_code < 500", ""]
    return "\n".join(lines)

def _fastapi_e2e(module: str, fapi: FastAPIModule) -> str:
    lines = [HEADER, "import pytest", "from fastapi.testclient import TestClient", f"from {module} import {fapi.app_name} as _app", "", "client = TestClient(_app)", ""]
    by_base = {}
    for r in fapi.routes:
        base = re.sub(r"/\{[^}]+\}", "", r.path.rstrip("/")) or "/"
        by_base.setdefault(base, {}).setdefault(r.method, []).append(r.path)
    wrote = 0
    for base, m in by_base.items():
        if m.get("post") and m.get("get"):
            p = re.sub(r"\{[^}]+\}", "1", m["post"][0]); g = re.sub(r"\{[^}]+\}", "1", m["get"][0])
            lines += [f"def test_flow_{wrote+1}_post_then_get():", f'    assert client.post("{p}", json={{}}).status_code < 500', f'    assert client.get("{g}").status_code < 500', ""]
            wrote += 1
    if wrote == 0:
        gets = [r for r in fapi.routes if r.method == "get"]
        if gets:
            lines += ["def test_smoke_gets():"]
            for r in gets[:10]:
                u = re.sub(r"\{[^}]+\}", "1", r.path)
                lines += [f'    assert client.get("{u}").status_code < 500']
            lines += [""]
        else:
            lines += ["def test_e2e_placeholder():", "    assert True", ""]
    return "\n".join(lines)

def _flask_integration(module: str, flask_m: FlaskModule) -> str:
    lines = [HEADER, "import pytest", "from flask.testing import FlaskClient", f"from {module} import {flask_m.app_name} as _app", "", "client = _app.test_client()", ""]
    for i, r in enumerate(flask_m.routes, 1):
        url = r.path if r.path.startswith("/") else "/" + r.path
        lines += [f"def test_route_{i}_no_500():", f'    res = client.get("{url}")', "    assert res.status_code < 500", ""]
    return "\n".join(lines)

def _flask_e2e(module: str, flask_m: FlaskModule) -> str:
    lines = [HEADER, "import pytest", f"from {module} import {flask_m.app_name} as _app", "", "client = _app.test_client()", "", "def test_e2e_smoke_routes():"]
    for r in flask_m.routes[:10]:
        url = r.path if r.path.startswith("/") else "/" + r.path
        lines += [f'    assert client.get("{url}").status_code < 500']
    lines += [""]
    return "\n".join(lines)

def _django_integration(urls: List[str]) -> str:
    lines = [HEADER, "import pytest", "from django.test import Client", "", "client = Client()", ""]
    idx = 1
    for u in urls[:30]:
        if u.startswith("[re_path]"):
            lines += [f"def test_re_path_{idx}_placeholder():", "    assert True", ""]
        else:
            lines += [f"def test_get_{idx}_no_500():", f'    assert client.get("{u}").status_code < 500', ""]
        idx += 1
    return "\n".join(lines)

def _django_e2e(urls: List[str]) -> str:
    lines = [HEADER, "import pytest", "from django.test import Client", "", "client = Client()", ""]
    gets = [u for u in urls if not u.startswith("[re_path]")]
    if gets:
        lines += ["def test_e2e_smoke():"]
        for u in gets[:5]:
            lines += [f'    assert client.get("{u}").status_code < 500']
        lines += [""]
    else:
        lines += ["def test_e2e_placeholder():", "    assert True", ""]
    return "\n".join(lines)

def _cli_click_integration(module: str) -> str:
    return HEADER + f"""
import pytest
from click.testing import CliRunner
import importlib

def test_click_help():
    try:
        mod = importlib.import_module("{module}")
    except Exception:
        pytest.skip("Cannot import module")
    runner = CliRunner()
    for name in ("cli","app","main"):
        cmd = getattr(mod, name, None)
        if cmd is not None:
            res = runner.invoke(cmd, ["--help"])
            assert res.exit_code == 0
            return
    pytest.skip("No click command object found")
""".lstrip()

def _cli_typer_integration(module: str, app_name: str) -> str:
    return HEADER + f"""
import pytest
from typer.testing import CliRunner
from {module} import {app_name} as app

def test_typer_help():
    runner = CliRunner()
    res = runner.invoke(app, ["--help"])
    assert res.exit_code == 0
""".lstrip()

def _cli_argparse_integration(module: str) -> str:
    return HEADER + f"""
import pytest, sys, importlib

def test_argparse_main_help(monkeypatch):
    mod = importlib.import_module("{module}")
    main = getattr(mod, "main", None)
    if main is None:
        pytest.skip("No main() for argparse detected")
    monkeypatch.setattr(sys, "argv", ["prog", "-h"])
    try:
        main()
    except SystemExit as e:
        assert e.code == 0
""".lstrip()

def _ensure_django_conftest(out_root: Path, settings_module: Optional[str]):
<<<<<<< HEAD
=======
    out_root.mkdir(parents=True, exist_ok=True)
>>>>>>> c808094 (new commit)
    p = out_root / "conftest.py"
    if p.exists(): return
    content = f'''{HEADER}import os, django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{settings_module or 'settings'}")
django.setup()
'''
    p.write_text(content, encoding="utf-8")

def _write_if_absent(path: Path, content: str) -> bool:
    if path.exists(): return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8"); return True

def _module_name(fp: Path, root: Path) -> str:
    return ".".join(fp.relative_to(root).with_suffix("").parts)

def generate_pytests(repo_root: Path, analyses: List[Dict[str, Any]], out_dir: Path) -> List[Path]:
    unit_dir = out_dir / "unit"
    integ_dir = out_dir / "integration"
    e2e_dir  = out_dir / "e2e"
    created: List[Path] = []

    # Django project-level tests
    dj = _detect_django(repo_root)
    if dj:
        all_urls: List[str] = []
        for up in dj.urls_files:
            all_urls.extend(_django_urls_from_file(up))
        _ensure_django_conftest(out_dir, dj.settings_module)
        ctx = {"settings_module": dj.settings_module, "urls": all_urls[:200]}
        ai_in = _ai_integ("django", ctx) or _django_integration(all_urls)
        ai_e2e = _ai_e2e("django", ctx) or _django_e2e(all_urls)
        if _write_if_absent(integ_dir / "test_django_integration.py", ai_in): created.append(integ_dir / "test_django_integration.py")
        if _write_if_absent(e2e_dir / "test_django_e2e.py", ai_e2e): created.append(e2e_dir / "test_django_e2e.py")

    for a in analyses:
        path = a.get("path", "")
        if not path: continue
        if "tests/" in path or "/migrations/" in path or "\\migrations\\" in path:
            continue
        src = a.get("source", "")
        fp = Path(path); module = _module_name(fp, repo_root)

        # ----- UNIT -----
        code = _ai_unit(module, a) or _unit_fallback(module, a)
        uf = unit_dir / f"test_{fp.stem}.py"
        if _write_if_absent(uf, code): created.append(uf)

        # ----- INTEGRATION/E2E per module -----
        fapi = _extract_fastapi(src)
        if fapi:
            ctx = {"module": module, "app_name": fapi.app_name, "routes": [{"m": r.method, "p": r.path} for r in fapi.routes[:100]]}
            in_code = _ai_integ("fastapi", ctx) or _fastapi_integration(module, fapi)
            e2e_code = _ai_e2e("fastapi", ctx) or _fastapi_e2e(module, fapi)
            if _write_if_absent(integ_dir / f"test_{fp.stem}_integration.py", in_code): created.append(integ_dir / f"test_{fp.stem}_integration.py")
            if _write_if_absent(e2e_dir / f"test_{fp.stem}_e2e.py", e2e_code): created.append(e2e_dir / f"test_{fp.stem}_e2e.py")
            continue

        flask_m = _extract_flask(src)
        if flask_m:
            ctx = {"module": module, "app_name": flask_m.app_name, "routes": [r.path for r in flask_m.routes[:100]]}
            in_code = _ai_integ("flask", ctx) or _flask_integration(module, flask_m)
            e2e_code = _ai_e2e("flask", ctx) or _flask_e2e(module, flask_m)
            if _write_if_absent(integ_dir / f"test_{fp.stem}_integration.py", in_code): created.append(integ_dir / f"test_{fp.stem}_integration.py")
            if _write_if_absent(e2e_dir / f"test_{fp.stem}_e2e.py", e2e_code): created.append(e2e_dir / f"test_{fp.stem}_e2e.py")
            continue

        # CLI Typer
        m = TYPER_APP_RE.search(src)
        if m:
            app_name = m.group(1)
            ctx = {"module": module, "app_name": app_name}
            in_code = _ai_integ("typer", ctx) or _cli_typer_integration(module, app_name)
            e2e_code = _ai_e2e("typer", ctx) or in_code
            if _write_if_absent(integ_dir / f"test_{fp.stem}_integration.py", in_code): created.append(integ_dir / f"test_{fp.stem}_integration.py")
            if _write_if_absent(e2e_dir / f"test_{fp.stem}_e2e.py", e2e_code): created.append(e2e_dir / f"test_{fp.stem}_e2e.py")
            continue

        # CLI Click
        if _has_click(src):
            ctx = {"module": module}
            in_code = _ai_integ("click", ctx) or _cli_click_integration(module)
            e2e_code = _ai_e2e("click", ctx) or in_code
            if _write_if_absent(integ_dir / f"test_{fp.stem}_integration.py", in_code): created.append(integ_dir / f"test_{fp.stem}_integration.py")
            if _write_if_absent(e2e_dir / f"test_{fp.stem}_e2e.py", e2e_code): created.append(e2e_dir / f"test_{fp.stem}_e2e.py")
            continue

        # CLI argparse
        if _has_argparse(src):
            ctx = {"module": module}
            in_code = _ai_integ("argparse", ctx) or _cli_argparse_integration(module)
            e2e_code = _ai_e2e("argparse", ctx) or in_code
            if _write_if_absent(integ_dir / f"test_{fp.stem}_integration.py", in_code): created.append(integ_dir / f"test_{fp.stem}_integration.py")
            if _write_if_absent(e2e_dir / f"test_{fp.stem}_e2e.py", e2e_code): created.append(e2e_dir / f"test_{fp.stem}_e2e.py")
            continue

    return created
