from __future__ import annotations

"""
Generator that produces **three types of tests** for Python projects:

- Unit tests -> tests/generated/unit/
- Integration tests (FastAPI-aware) -> tests/generated/integration/
- E2E smoke flows (FastAPI-aware) -> tests/generated/e2e/

Backwards-compatible with orchestrator: we keep the public entry
`generate_pytests(repo_root, analyses, out_dir)` and simply create
subfolders under `out_dir`.
"""
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Any, List, Optional
import re

try:
    from providers.azure_openai_provider import AzureProvider
except Exception:
    AzureProvider = None  # type: ignore

HEADER = "# Auto-generated by AI-TestGen. Edit as needed.\n\n"

ROUTE_DECORATOR_RE = re.compile(
    r"@\s*([A-Za-z_][\w\.]*)\.(get|post|put|delete|patch)\s*\(\s*([\'\"])(.*?)\3",
    re.IGNORECASE | re.MULTILINE,
)
FASTAPI_APP_RE = re.compile(r"\b([A-Za-z_][\w]*)\s*=\s*FastAPI\s*\(")

@dataclass
class Route:
    owner: str
    method: str
    path: str

@dataclass
class FastAPIModule:
    app_name: str
    routes: List[Route]

def _extract_fastapi_info(source: str) -> Optional[FastAPIModule]:
    app_name = "app"
    m = FASTAPI_APP_RE.search(source)
    if m:
        app_name = m.group(1)

    routes: List[Route] = []
    for dec_owner, method, _, path in ROUTE_DECORATOR_RE.findall(source):
        routes.append(Route(owner=dec_owner.split(".")[-1], method=method.lower(), path=path))

    if not routes:
        return None
    return FastAPIModule(app_name=app_name, routes=routes)

def _unit_tests_ai_or_stub(module_name: str, analysis: Dict[str, Any]) -> str:
    source = analysis.get("source", "")
    ai_code: Optional[str] = None
    if AzureProvider is not None:
        try:
            prov = AzureProvider()
            if getattr(prov, "available", lambda: False)():
                enriched = dict(analysis)
                enriched["test_kind"] = "unit"
                ai_code = prov.generate_pytest(analysis.get("path", module_name), source, enriched)
        except Exception:
            ai_code = None

    if ai_code:
        code = ai_code
    else:
        fn_tests = []
        for fn in analysis.get("functions", []):
            fn_tests.append(f"""
                def test_{fn}_basic():
                    assert callable({fn})
            """)
        if not fn_tests:
            fn_tests.append("""
                def test_module_imports():
                    assert True
            """)
        code = HEADER + "import pytest\n\n" + "\n".join(t.strip() for t in fn_tests)

    if f"import {module_name}" not in code and f"from {module_name}" not in code:
        code = f"from {module_name} import *\n\n" + code
    return code

def _integration_tests_fastapi(module_name: str, fm: FastAPIModule) -> str:
    lines = [
        HEADER,
        "import pytest",
        "from fastapi.testclient import TestClient",
        f"from {module_name} import {fm.app_name} as _the_app",
        "",
        "client = TestClient(_the_app)",
        "",
    ]

    def sample_body() -> str:
        return "{}"

    def sample_path(path: str) -> str:
        return re.sub(r"\{[^}]+\}", "1", path)

    for idx, r in enumerate(fm.routes, start=1):
        url = sample_path(r.path)
        method = r.method.lower()
        test_name = f"test_{method}_{idx}_status_non_5xx"
        if method in {"get", "delete"}:
            call = f"res = client.{method}(\"{url}\")"
        elif method in {"post", "put", "patch"}:
            call = f"res = client.{method}(\"{url}\", json={sample_body()})"
        else:
            call = f"res = client.request(\"{method}\", \"{url}\")"

        lines.append("\n".join([
            f"def {test_name}():",
            f"    {call}",
            "    assert res.status_code < 500",
        ]))
    return "\n\n".join(lines) + "\n"

def _e2e_tests_fastapi(module_name: str, fm: FastAPIModule) -> str:
    lines = [
        HEADER,
        "import pytest",
        "from fastapi.testclient import TestClient",
        f"from {module_name} import {fm.app_name} as _the_app",
        "",
        "client = TestClient(_the_app)",
        "",
    ]

    def base_of(path: str) -> str:
        return re.sub(r"/\{[^}]+\}", "", path.rstrip("/")) or "/"

    routes = fm.routes
    by_base: Dict[str, Dict[str, List[str]]] = {}
    for r in routes:
        b = base_of(r.path)
        by_base.setdefault(b, {}).setdefault(r.method, []).append(r.path)

    flows_written = 0
    for base, methods in by_base.items():
        posts = methods.get("post", [])
        gets = methods.get("get", [])
        if posts and gets:
            post_path = re.sub(r"\{[^}]+\}", "1", posts[0])
            get_path = re.sub(r"\{[^}]+\}", "1", gets[0])
            lines.append("\n".join([
                f"def test_flow_{flows_written+1}_post_then_get():",
                f"    res_create = client.post(\"{post_path}\", json={{}})",
                "    assert res_create.status_code < 500",
                f"    res_list = client.get(\"{get_path}\")",
                "    assert res_list.status_code < 500",
            ]))
            flows_written += 1

    if flows_written == 0:
        get_routes = [r for r in routes if r.method == "get"]
        if get_routes:
            lines.append("def test_smoke_all_get_endpoints():")
            for r in get_routes:
                url = re.sub(r"\{[^}]+\}", "1", r.path)
                lines.append(f"    assert client.get(\"{url}\").status_code < 500")
        else:
            lines.append("""
                def test_no_e2e_routes_found():
                    assert True
            """.strip())

    return "\n\n".join(lines) + "\n"

def relative_module_name(file_path: Path, repo_root: Path) -> str:
    rel = file_path.relative_to(repo_root).with_suffix("")
    return ".".join(rel.parts)

def _write_if_absent(path: Path, content: str) -> bool:
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True

def generate_pytests(repo_root: Path, analyses: List[Dict[str, Any]], out_dir: Path) -> List[Path]:
    unit_dir = out_dir / "unit"
    integ_dir = out_dir / "integration"
    e2e_dir = out_dir / "e2e"

    created: List[Path] = []

    for a in analyses:
        if a.get("has_tests"):
            continue
        src_path = Path(a["path"])
        module_name = relative_module_name(src_path, repo_root)
        source = a.get("source", "")

        unit_code = _unit_tests_ai_or_stub(module_name, a)
        unit_file = unit_dir / f"test_{src_path.stem}.py"
        if _write_if_absent(unit_file, unit_code):
            created.append(unit_file)

        fapi = _extract_fastapi_info(source)
        if fapi:
            integ_code = _integration_tests_fastapi(module_name, fapi)
            integ_file = integ_dir / f"test_{src_path.stem}_integration.py"
            if _write_if_absent(integ_file, integ_code):
                created.append(integ_file)

            e2e_code = _e2e_tests_fastapi(module_name, fapi)
            e2e_file = e2e_dir / f"test_{src_path.stem}_e2e.py"
            if _write_if_absent(e2e_file, e2e_code):
                created.append(e2e_file)

    return created
